
import React from 'react';
import { CheckCircle2, RefreshCw, Loader2, MousePointerClick } from 'lucide-react';
import { GeneratedImage } from '../types';

export interface NanoPreviewGridProps {
  images: GeneratedImage[];
  selectedId: string | null;
  onSelect: (image: GeneratedImage) => void;
  isLoading: boolean;
  onRegenerate: () => void;
}

export const NanoPreviewGrid: React.FC<NanoPreviewGridProps> = ({ images, selectedId, onSelect, isLoading, onRegenerate }) => {
  return (
    <div className="space-y-4">
      <div className="flex justify-between items-end">
        <div>
          <h3 className="text-sm font-bold text-gray-900">Step 1: Select Draft Variant</h3>
          <p className="text-xs text-gray-500">Generated by Gemini Nano. Pick the best composition to refine.</p>
        </div>
        {!isLoading && images.length > 0 && (
          <button onClick={onRegenerate} className="text-xs text-purple-600 font-bold hover:underline flex items-center gap-1">
            <RefreshCw size={12} /> Regenerate
          </button>
        )}
      </div>

      {isLoading ? (
        <div className="grid grid-cols-2 gap-4 animate-pulse">
          {[1, 2, 3, 4].map(i => (
            <div key={i} className="aspect-square bg-gray-100 rounded-xl border border-gray-200 flex flex-col items-center justify-center gap-2">
              <Loader2 className="animate-spin text-gray-300" />
              <span className="text-xs font-bold text-gray-400 uppercase tracking-wider">Generating Variant {i}...</span>
            </div>
          ))}
        </div>
      ) : images.length > 0 ? (
        <div className="grid grid-cols-2 gap-4">
          {images.map((img, index) => {
            const isSelected = selectedId === img.id;
            return (
              <div 
                key={img.id} 
                onClick={() => onSelect(img)}
                className={`group relative aspect-square rounded-xl overflow-hidden cursor-pointer transition-all duration-300 ${
                  isSelected 
                    ? 'ring-4 ring-purple-500 ring-offset-2 shadow-xl scale-[1.02]' 
                    : 'border border-gray-200 hover:border-purple-300 hover:shadow-md'
                }`}
              >
                <img 
                  src={`data:image/png;base64,${img.base64}`} 
                  alt={`Variant ${index + 1}`} 
                  className="w-full h-full object-cover" 
                />
                
                {/* Variant Label */}
                <div className="absolute top-3 left-3 bg-black/60 backdrop-blur px-2 py-1 rounded text-[10px] font-bold text-white uppercase tracking-wider">
                  V{index + 1}
                </div>

                {/* Selection Overlay */}
                <div className={`absolute inset-0 transition-colors flex items-center justify-center ${isSelected ? 'bg-purple-900/20' : 'bg-black/0 group-hover:bg-black/10'}`}>
                  {isSelected ? (
                    <div className="bg-purple-600 text-white p-2 rounded-full shadow-lg transform scale-100 transition-transform">
                      <CheckCircle2 size={24} />
                    </div>
                  ) : (
                    <div className="bg-white/90 text-gray-900 px-4 py-2 rounded-full text-xs font-bold shadow-lg opacity-0 group-hover:opacity-100 transform translate-y-2 group-hover:translate-y-0 transition-all flex items-center gap-2">
                      <MousePointerClick size={14} /> Select
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      ) : (
        <div className="text-center py-16 bg-gray-50 rounded-2xl border-2 border-dashed border-gray-200">
          <div className="w-12 h-12 bg-gray-200 rounded-full flex items-center justify-center mx-auto mb-3">
            <Loader2 size={20} className="text-gray-400" />
          </div>
          <p className="text-gray-500 text-sm font-medium">No drafts generated yet.</p>
          <p className="text-gray-400 text-xs">Click "Generate Previews" to start.</p>
        </div>
      )}
    </div>
  );
};
